import { describe, expect, it } from "vitest";
import { summarize, splitVat, addVat, getReportingPeriods, getCurrentPeriod, compareToPrevious, toCents, type CalcTransaction } from "./calc";
const row = (patch: Partial<CalcTransaction> = {}): CalcTransaction => ({ direction: "expense", amount_before_vat: 100, vat_amount: 18, amount_total: 118, vat_deductible_percent: 100, currency: "ILS", is_verified: true, category_id: null, ...patch });
describe("central calculation engine (monetary results in agorot)", () => {
    it("one income and expense, profile rates", () => { const s = summarize([row({ direction: "income", amount_before_vat: 1000, vat_amount: 180, amount_total: 1180 }), row()], { incomeTaxAdvanceRate: 5, taxReserveRate: 30 }); expect(s).toMatchObject({ incomeBeforeVat: 100000, outputVat: 18000, expenseBeforeVat: 10000, inputVat: 1800, vatDue: 16200, profitBeforeTax: 90000, taxAdvance: 5000, taxReserve: 27000, countIncome: 1, countExpense: 1 }); });
    it("66 and 25 percent recognized per expense", () => { expect(summarize([row({ vat_deductible_percent: 66 }), row({ vat_deductible_percent: 25 })]).inputVat).toBe(1188 + 450); });
    it("negative VAT and no negative tax reserve", () => { const s = summarize([row()]); expect(s.vatDue).toBe(-1800); expect(s.profitBeforeTax).toBe(-10000); expect(s.taxReserve).toBe(0); });
    it("empty period", () => { const s = summarize([]); for (const [key, value] of Object.entries(s))
        expect(value).toEqual(key === "byCategory" ? [] : 0); });
    it("117.65 inclusive at 18 percent", () => { expect(splitVat(117.65, 18)).toEqual({ amountBeforeVat: 9970, vatAmount: 1795, amountTotal: 11765 }); expect(addVat(99.70, 18).amountTotal).toBe(11765); });
    it("exact half-up ties and integer aggregates", () => { expect(toCents(1.005)).toBe(101); expect(toCents(-1.005)).toBe(-101); expect(summarize([row({ vat_amount: 0.01, vat_deductible_percent: 50 }), row({ vat_amount: 0.01, vat_deductible_percent: 50 })]).inputVat).toBe(2); expect(toCents(1e-7)).toBe(0); expect(() => toCents(Infinity)).toThrow(); });
    it("includes unverified rows and excludes foreign VAT, not converted ILS revenue", () => { const s = summarize([row({ is_verified: false }), row({ direction: "income", currency: "USD", amount_before_vat: 300, vat_amount: 54, amount_total: 354, is_verified: false })]); expect(s.unverifiedCount).toBe(2); expect(s.foreignCurrencyCount).toBe(1); expect(s.incomeBeforeVat).toBe(30000); expect(s.outputVat).toBe(0); expect(s.inputVat).toBe(1800); expect(s.vatDue).toBe(-1800); });
    it("foreign expense VAT is excluded from input and category VAT", () => { const s = summarize([row({ currency: "USD" })]); expect(s.inputVat).toBe(0); expect(s.byCategory[0].vatAmount).toBe(0); expect(s.expenseBeforeVat).toBe(10000); });
    it("legacy unconverted rows are counted but not added as ILS", () => { const s = summarize([row({ currency: "USD", currency_review_required: true, is_verified: false })]); expect(s.foreignCurrencyCount).toBe(1); expect(s.unverifiedCount).toBe(1); expect(s.currencyReviewCount).toBe(1); expect(s.expenseTotal).toBe(0); });
    it("category shares use pre-VAT expenses, including uncategorized", () => { const s = summarize([row({ category_id: "a" }), row({ amount_before_vat: 300 })]); expect(s.byCategory).toEqual([{ categoryId: "a", amountBeforeVat: 10000, vatAmount: 1800, count: 1, percentOfExpenses: 25 }, { categoryId: null, amountBeforeVat: 30000, vatAmount: 1800, count: 1, percentOfExpenses: 75 }]); });
    it("zero category denominator", () => { expect(summarize([row({ amount_before_vat: 0 })]).byCategory[0].percentOfExpenses).toBe(0); });
    it("monthly and bimonthly boundaries including leap year", () => { const p = getReportingPeriods(2024, "bimonthly"); expect(p).toHaveLength(6); expect(p[0]).toEqual({ start: "2024-01-01", end: "2024-02-29", name: "ינואר–פברואר 2024" }); expect(p[5].end).toBe("2024-12-31"); expect(getReportingPeriods(2025, "monthly")).toHaveLength(12); expect(getCurrentPeriod("2026-03-01", "bimonthly").start).toBe("2026-03-01"); expect(getCurrentPeriod("2026-12-31", "bimonthly").start).toBe("2026-11-01"); expect(getCurrentPeriod(new Date("2026-02-28T22:30:00Z"), "monthly").start).toBe("2026-03-01"); expect(() => getCurrentPeriod("2026-02-30", "monthly")).toThrow(); });
    it("percent comparisons, zero baseline and negative baseline", () => { const zero = summarize([]), expense = summarize([row()]); expect(compareToPrevious(zero, zero).vatDue).toBe(0); expect(compareToPrevious(expense, zero).expenseBeforeVat).toBeNull(); expect(compareToPrevious(zero, expense).expenseBeforeVat).toBe(-100); expect(compareToPrevious(zero, expense).vatDue).toBe(100); });
    it("does not mutate input and rejects precision overflow", () => { const input = Object.freeze([Object.freeze(row())]); expect(summarize(input).inputVat).toBe(1800); expect(() => toCents(Number.MAX_SAFE_INTEGER)).toThrow(); });
});
