import Link from "next/link";
import { formatCentsILS, formatCurrencyILS, formatDateDDMMYYYY } from "@/lib/format";
import type { DashboardData } from "@/lib/dashboard/load-dashboard";
import { PeriodPicker } from "./PeriodPicker";
import { MonthlyChart } from "./MonthlyChart";

const panel = "min-w-0 rounded-2xl border border-border bg-background p-5 sm:p-6";
const link = "rounded-lg text-primary underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-primary";
function Change({ value }: { value: number | null }): React.JSX.Element {
    if (value === null) return <p className="mt-3 text-xs text-foreground/60">אין בסיס להשוואה — התקופה הקודמת אפס</p>;
    return <p className="mt-3 text-sm text-foreground/70"><span aria-hidden="true">{value > 0 ? "↑" : value < 0 ? "↓" : "↔"}</span> {value === 0 ? "ללא שינוי" : `${value > 0 ? "עלייה" : "ירידה"} של ${new Intl.NumberFormat("he-IL", { maximumFractionDigits: 2 }).format(Math.abs(value))}%`} <span className="text-xs">מול התקופה הקודמת</span></p>;
}
function Attention({ data }: { data: DashboardData }): React.JSX.Element | null {
    const pending = data.documents.filter(document => document.status !== "failed");
    const failed = data.documents.filter(document => document.status === "failed");
    const groups = [
        { title: "מסמכים שממתינים לאישור", items: pending.map(document => ({ id: document.id, title: document.file_name, href: `/documents/${document.id}/review`, action: document.status === "processing" ? "צפייה במצב הזיהוי" : "בדיקה ואישור" })) },
        { title: "מסמכים שהזיהוי שלהם נכשל", items: failed.map(document => ({ id: document.id, title: document.file_name, href: `/documents/${document.id}/review`, action: "ניסיון נוסף או הזנה ידנית" })) },
        { title: "תנועות ללא קטגוריה", items: data.uncategorized.map(row => ({ id: row.id, title: `${row.counterparty_name} · ${formatDateDDMMYYYY(row.doc_date)}`, href: `/transactions/${row.id}`, action: "עריכת קטגוריה" })) },
        { title: "הכרה במע״מ שדורשת בדיקה", items: data.invalidDeduction.map(row => ({ id: row.id, title: `${row.counterparty_name} · ${row.doc_number ?? "ללא מספר מסמך"}`, href: `/transactions/${row.id}`, action: "בדיקת סוג המסמך ואחוז ההכרה" })) },
    ].filter(group => group.items.length > 0);
    if (!groups.length) return null;
    return <section className={`${panel} border-warning/40`} aria-labelledby="attention-title"><h2 id="attention-title" className="text-lg font-semibold">דורש טיפול</h2><p className="mt-1 text-sm text-foreground/60">תנועות לפי תאריך המסמך, ומסמכים שטרם אושרו לפי תאריך ההעלאה — בתקופה שנבחרה.</p><div className="mt-4 grid gap-4 md:grid-cols-2">{groups.map(group => <details key={group.title} open className="min-w-0 rounded-xl bg-warning/5 p-4"><summary className="cursor-pointer font-medium">{group.title} <span className="tabular-nums">({group.items.length})</span></summary><ul className="mt-3 max-h-64 space-y-3 overflow-y-auto">{group.items.map(item => <li key={item.id} className="min-w-0 border-t border-border pt-3"><p className="truncate text-sm" dir="auto" title={item.title}>{item.title}</p><Link className={`${link} mt-1 inline-block text-sm`} href={item.href}>{item.action}</Link></li>)}</ul></details>)}</div></section>;
}
export function DashboardView({ data }: { data: DashboardData }): React.JSX.Element {
    const { profile, window, totals, comparison } = data;
    const rangeLabel = `${formatDateDDMMYYYY(window.selected.start)}–${formatDateDDMMYYYY(window.selected.end)}`;
    const rangeQuery = new URLSearchParams({ preset: "custom", start: window.selected.start, end: window.selected.end }).toString();
    const names = new Map(data.categories.map(category => [category.id, category.name]));
    const categories = [...totals.byCategory].sort((a, b) => b.amountBeforeVat - a.amountBeforeVat);
    const cards = [
        { title: totals.vatDue < 0 ? "החזר מע״מ צפוי" : "מע״מ לתשלום", value: Math.abs(totals.vatDue), change: comparison.vatDue, tone: totals.vatDue < 0 ? "text-income" : "text-primary", featured: true },
        { title: "הכנסות לפני מע״מ", value: totals.incomeBeforeVat, change: comparison.incomeBeforeVat, tone: "text-income", featured: false },
        { title: "הוצאות לפני מע״מ", value: totals.expenseBeforeVat, change: comparison.expenseBeforeVat, tone: "text-expense", featured: false },
        { title: "רווח לפני מס", value: totals.profitBeforeTax, change: comparison.profitBeforeTax, tone: totals.profitBeforeTax < 0 ? "text-expense" : "text-foreground", featured: false },
    ];
    return <div className="flex min-w-0 flex-col gap-6 tabular-nums">
        <header className="flex flex-col gap-4"><div><p className="mb-1 text-sm text-foreground/60">תמונת המצב של העסק</p><h1 className="break-words text-2xl font-bold sm:text-3xl">שלום, {profile.business_name?.trim() || "העסק שלי"}</h1></div><PeriodPicker key={`${window.preset}-${window.selected.start}-${window.selected.end}`} window={window} /><p className="text-sm text-foreground/60">{window.selected.name} · <span dir="ltr">{rangeLabel}</span></p></header>
        {data.isFirstVisit ? <section className={`${panel} border-primary/30 bg-primary/5`}><h2 className="text-2xl font-semibold">בואי נעשה סדר בחשבוניות</h2><p className="mt-2 text-foreground/70">עדיין אין תנועות בעסק שלך. כך מתחילים:</p><ol className="my-6 grid list-inside list-decimal gap-4 sm:grid-cols-3"><li><strong>מעלים מסמך</strong><p className="mt-1 text-sm">צלמי חשבונית או בחרי קובץ מהמחשב.</p></li><li><strong>בודקים ומאשרים</strong><p className="mt-1 text-sm">בדקי את הפרטים שזוהו ותקני לפי הצורך.</p></li><li><strong>רואים את מצב העסק</strong><p className="mt-1 text-sm">ההכנסות, ההוצאות והמע״מ יתעדכנו כאן.</p></li></ol><Link href="/upload" className="inline-flex rounded-xl bg-primary px-6 py-3 text-lg font-medium text-white">העלאת המסמך הראשון</Link>{data.documents.length > 0 && <p className="mt-4"><Link href="/documents" className={link}>כבר העלית מסמכים? המשיכי לאישור שלהם</Link></p>}</section> : <>
            <div className="grid min-w-0 gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card => <section key={card.title} className={`${panel} ${card.featured ? "border-primary/40 bg-primary/5 ring-1 ring-primary/15" : ""}`}><h2 className="text-sm font-medium text-foreground/70">{card.title}</h2><p className={`mt-3 break-words text-3xl font-bold tracking-tight ${card.tone}`} dir="ltr">{formatCentsILS(card.value)}</p><Change value={card.change} /></section>)}</div>
            <p className="-mt-3 text-xs text-foreground/60">השוואה ל־{formatDateDDMMYYYY(window.previous.start)}–{formatDateDDMMYYYY(window.previous.end)}. ההשוואה היא בין טווחים מלאים; התקופה הנוכחית עשויה עדיין להיות חלקית.</p>
            {(totals.unverifiedCount > 0 || totals.foreignCurrencyCount > 0 || totals.currencyReviewCount > 0) && <div role="status" className="rounded-xl border border-warning/30 bg-warning/5 p-4 text-sm">{totals.unverifiedCount > 0 && <p>הסיכומים כוללים {totals.unverifiedCount} תנועות שטרם אושרו.</p>}{totals.foreignCurrencyCount > 0 && <p>{totals.foreignCurrencyCount} תנועות במטבע זר אינן נכללות בסיכומי המע״מ. סכומים שהומרו לשקלים נכללים בהכנסות ובהוצאות.</p>}{totals.currencyReviewCount > 0 && <p>{totals.currencyReviewCount} תנועות ישנות דורשות בדיקת מטבע ואינן נכללות בסכומים.</p>}</div>}
            <section className={panel}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{window.preset === "period" ? "התקופה הנוכחית לדיווח" : "סיכום התקופה שנבחרה"}</h2><p className="mt-1 text-sm text-foreground/60">{window.selected.name} · {rangeLabel}</p></div><Link href={`/export?${rangeQuery}`} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white">ייצא לרואה החשבון</Link></div><dl className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{[
                ["מע״מ עסקאות", totals.outputVat], ["פחות מע״מ תשומות", totals.inputVat], [totals.vatDue < 0 ? "שווה: החזר מע״מ צפוי" : "שווה: מע״מ לתשלום", Math.abs(totals.vatDue)], ["הערכת מקדמות מס הכנסה", totals.taxAdvance], ["כרית מס", totals.taxReserve],
            ].map(([label, amount]) => <div key={String(label)}><dt className="text-sm text-foreground/70">{label}</dt><dd className="mt-2 break-words text-xl font-semibold">{formatCentsILS(Number(amount))}</dd></div>)}</dl><p className="mt-5 text-sm">{window.daysRemaining > 0 ? `נותרו ${window.daysRemaining} ימים עד סוף התקופה` : "התקופה מסתיימת היום או שכבר הסתיימה"}</p><p className="mt-2 text-xs text-foreground/60">מקדמות לפי {profile.income_tax_advance_rate}% מההכנסות לפני מע״מ; כרית מס לפי {profile.tax_reserve_rate}% מהרווח החיובי. אלו הערכות לפי ההגדרות שלך. הייצוא ייבנה בשלב הבא.</p></section>
            <section className={panel}><h2 className="text-lg font-semibold">הכנסות מול הוצאות</h2><p className="mb-5 mt-1 text-sm text-foreground/60">12 חודשים עד {formatDateDDMMYYYY(window.chartThrough)} · לפני מע״מ · החודש האחרון עשוי להיות חלקי</p><MonthlyChart data={data.chart} /></section>
            <div className="grid min-w-0 gap-6 lg:grid-cols-2"><section className={panel}><h2 className="mb-5 text-lg font-semibold">הוצאות לפי קטגוריה</h2>{categories.length === 0 ? <p className="text-sm text-foreground/60">אין הוצאות בתקופה שנבחרה.</p> : <ul className="space-y-5">{categories.map(category => <li key={category.categoryId ?? "uncategorized"}><div className="mb-2 flex flex-wrap justify-between gap-2 text-sm"><span className="break-words">{names.get(category.categoryId ?? "") ?? "ללא קטגוריה"}</span><span>{formatCentsILS(category.amountBeforeVat)} · {category.percentOfExpenses}%</span></div><div role="meter" aria-label={names.get(category.categoryId ?? "") ?? "ללא קטגוריה"} aria-valuemin={0} aria-valuemax={100} aria-valuenow={category.percentOfExpenses} className="h-2 overflow-hidden rounded-full bg-foreground/5"><div className="h-full rounded-full bg-expense/70" style={{ width: `${Math.min(100, Math.max(0, category.percentOfExpenses))}%` }} /></div></li>)}</ul>}<p className="mt-4 text-xs text-foreground/60">סכומים ואחוזים מתוך ההוצאות לפני מע״מ.</p></section>
            <section className={panel}><div className="mb-4 flex flex-wrap justify-between gap-2"><h2 className="text-lg font-semibold">5 התנועות האחרונות</h2><Link href={`/transactions?${rangeQuery}`} className={`${link} text-sm`}>לכל התנועות</Link></div>{data.latest.length === 0 ? <p className="text-sm text-foreground/60">אין תנועות בתקופה שנבחרה. אפשר לבחור תקופה אחרת.</p> : <ul className="divide-y divide-border">{data.latest.map(row => <li key={row.id}><Link href={`/transactions/${row.id}`} className="flex min-w-0 flex-wrap items-center justify-between gap-2 rounded-lg py-3 focus-visible:outline-2 focus-visible:outline-primary"><div className="min-w-0 flex-1"><p className="truncate font-medium">{row.counterparty_name}</p><p className="mt-1 text-xs text-foreground/60">{formatDateDDMMYYYY(row.doc_date)} · {row.direction === "income" ? "הכנסה" : "הוצאה"}{!row.is_verified && " · טרם אושרה"}</p></div><span className={`text-sm font-medium ${row.direction === "income" ? "text-income" : "text-expense"}`}>{row.currency_review_required ? "דרושה בדיקת מטבע" : formatCurrencyILS(row.amount_total)}</span></Link></li>)}</ul>}<p className="mt-3 text-xs text-foreground/60">לפי תאריך המסמך; הסכום כולל מע״מ.</p></section></div>
        </>}
        <Attention data={data} />
    </div>;
}
